import '../styles/globals/globals.scss';
import type {AppProps} from 'next/app';
import Head from 'next/head';
import Layout from '../components/Layout';
import {ThemeProvider} from '@mui/material/styles';
import theme from '../styles/globals/theme';
import Header from '../components/Header';
import Footer from '../components/Footer';
import createEmotionCache from '../styles/globals/createEmotionCache';
import {CacheProvider} from '@emotion/react';
import CssBaseline from '@mui/material/CssBaseline';

const clientSideEmotionCache = createEmotionCache();

export default function MyApp({Component, pageProps}: AppProps) {
  return (
    <CacheProvider value={clientSideEmotionCache}>
      <Head>
        <title>dubois.wedding</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
      </Head>
      <ThemeProvider theme={theme}>
        <CssBaseline />
        <Header />
        <Layout>
          <Component {...pageProps} />
        </Layout>
        <Footer />
      </ThemeProvider>
    </CacheProvider>
  );
}
