name: Cypress Tests

on: [pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        uses: bahmutov/npm-install@v1.4.5
      - name: Cypress run
        uses: cypress-io/github-action@v2
        timeout-minutes: 5
        with:
          build: yarn build
          start: yarn e2e:headless